language: python
python:
  - "3.8"
env:
  global:
    - HOST=127.0.0.1
    - PORT=8080
before_install:
  - pip install poetry
install:
  - |
    python -m venv venv
    . venv/bin/activate
    poetry install
script:
jobs:
  include:
    - stage: Testing
      name: bandit
      script: | 
              . venv/bin/activate
              bandit -r aws
    - name: black 
      script: | 
              . venv/bin/activate
              black --check aws tests
    - name: flake8
      script: | 
              . venv/bin/activate
              flake8 --statistics aws tests
    - name: mypy
      script: | 
              . venv/bin/activate
              mypy aws tests
    - name: pylint
      script: | 
              . venv/bin/activate
              pylint aws tests
    - name: safety
      script: | 
              . venv/bin/activate
              safety check
    - name: pytest
      script: | 
              . venv/bin/activate
              pytest --cov --reruns 3
