language: python
python:
  - "3.8"
env:
  global:
    - HOST=127.0.0.1
    - PORT=8080
before_install:
  - pip install poetry
  - poetry config virtualenvs.in-project true
install:
  - poetry install
script:
jobs:
  include:
    - stage: Tests
      name: "bandit"
      script: bandit -r aws
    - stage: Tests
      name: "black" 
      script: black --check aws tests
    - stage: Tests
      name: "flake8"
      script: flake8 --statistics aws tests
    - stage: Tests
      name: "mypy"
      script: mypy aws tests
    - stage: Tests
      name: "pylint"
      script: pylint aws tests
    - stage: Tests
      name: "safety"
      script: safety check
    - stage: Tests
      name: "pytest"
      script: pytest --cov --reruns 3
